# services:
#   frontend:
#     build: 
#       context: .
#       dockerfile: Dockerfile
#       args:
#         USER_ID: 1000
#         GROUP_ID: 1000
#     container_name: angular-dev
#     ports:
#       - "4200:4200"
#     volumes:
#       - .:/app
#       - /app/node_modules
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#     command: npm start
services:
  frontend:
    build: 
      context: .
      dockerfile: "Dockerfile"
      args:
        GROUP_ID: 1000
        USER_ID: 1000
    ports:
      - "4200:4200"
    volumes:
      - "./:/app:cached"
    command: start