root = "."
tmp_dir = "tmp"

[build]
  cmd         = "go build -o ./tmp/api ./cmd/api"
  bin         = "./tmp/api"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", "migrations"]
  delay       = 500
  kill_delay  = "500ms"
  send_interrupt = true

[log]
  time = true

[color]
  main    = "magenta"
  watcher = "cyan"
  build   = "yellow"
  runner  = "green"

[misc]
  clean_on_exit = true
